### ISSUE TITLE
Empty values at first loading

### ISSUE THREAD

**Issue by kramarmm** [Artinov/weather-app-kramarmm#1]
How can I fill this empty values? 
![image](https://cloud.githubusercontent.com/assets/25547238/23485774/8e0e40d8-fee5-11e6-8461-92b7efa852c0.png)

**Comment by kramarmm** [comment]
Maybe I can determine a user current location? Or  this impossible with javascript?
![image](https://cloud.githubusercontent.com/assets/25547238/23485832/ed997266-fee5-11e6-98a0-17891736a81d.png)

**Comment by eko24ive** [comment]
It possible to get user geolocation in modern browsers, you cant take a look at this links:
- https://www.w3schools.com/html/html5_geolocation.asp
- https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation

Requesting user location is result with showing similar popup:
![image](https://cloud.githubusercontent.com/assets/25591824/23492143/647b15ae-ff0b-11e6-83b8-224dfe64930a.png)

And you only can get user location if user allows you to get access to his geolocation.

There are one fallback technique, which allows you to get user location which is based on user IP address.   You can get more information about it on this stackoverflow question:
http://stackoverflow.com/questions/391979/how-to-get-clients-ip-address-using-javascript-only

**Comment by kramarmm** [comment]
Thank you for help. It works!
Can you check my code on readability and simplification maybe.

**Comment by eko24ive** [comment]
Sure, I create appropriate issues if there any
